/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as InstallRouteImport } from './routes/install'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DivineRouteImport } from './routes/divine'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfileMembershipRouteImport } from './routes/profile.membership'
import { Route as HistoryIdRouteImport } from './routes/history.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DivineRoute = DivineRouteImport.update({
  id: '/divine',
  path: '/divine',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileMembershipRoute = ProfileMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => ProfileRoute,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/divine': typeof DivineRoute
  '/explore': typeof ExploreRoute
  '/history': typeof HistoryRouteWithChildren
  '/install': typeof InstallRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/history/$id': typeof HistoryIdRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/admin/': typeof AdminIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/divine': typeof DivineRoute
  '/explore': typeof ExploreRoute
  '/install': typeof InstallRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/history/$id': typeof HistoryIdRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/admin': typeof AdminIndexRoute
  '/history': typeof HistoryIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/divine': typeof DivineRoute
  '/explore': typeof ExploreRoute
  '/history': typeof HistoryRouteWithChildren
  '/install': typeof InstallRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/history/$id': typeof HistoryIdRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/admin/': typeof AdminIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/divine'
    | '/explore'
    | '/history'
    | '/install'
    | '/learn'
    | '/login'
    | '/profile'
    | '/history/$id'
    | '/profile/membership'
    | '/admin/'
    | '/history/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/divine'
    | '/explore'
    | '/install'
    | '/learn'
    | '/login'
    | '/history/$id'
    | '/profile/membership'
    | '/admin'
    | '/history'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/divine'
    | '/explore'
    | '/history'
    | '/install'
    | '/learn'
    | '/login'
    | '/profile'
    | '/history/$id'
    | '/profile/membership'
    | '/admin/'
    | '/history/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DivineRoute: typeof DivineRoute
  ExploreRoute: typeof ExploreRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  InstallRoute: typeof InstallRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divine': {
      id: '/divine'
      path: '/divine'
      fullPath: '/divine'
      preLoaderRoute: typeof DivineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/membership': {
      id: '/profile/membership'
      path: '/membership'
      fullPath: '/profile/membership'
      preLoaderRoute: typeof ProfileMembershipRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface ProfileRouteChildren {
  ProfileMembershipRoute: typeof ProfileMembershipRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileMembershipRoute: ProfileMembershipRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DivineRoute: DivineRoute,
  ExploreRoute: ExploreRoute,
  HistoryRoute: HistoryRouteWithChildren,
  InstallRoute: InstallRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
